### ISSUE TITLE
Accommodating alternatives to check profane words

### ISSUE THREAD

**Issue by ieshaan12** [ieshaan12/PyProfane#4]
People use other letters to avoid profane checkers like 3 for e, 1 for i,l and so on. Can someone make a list and integrate that into the code as well?

**Comment by RimorRes** [comment]
At your service good sir!
I'll try and help you with this one.

**Comment by ieshaan12** [comment]
@RimorRes thanks, I'll assign you if that's fine?

**Comment by RimorRes** [comment]
No problem!

**Comment by RimorRes** [comment]
Tis' done!
I've opened a pull request! #5 
I'm sorry for the awful commit message, it's been a while so I've kind of forgotten about commit messages and Markdown conventions...

**Comment by ieshaan12** [comment]
@RimorRes Awesome work!
